### ISSUE TITLE
What are the format and unit of KRT? 

### ISSUE THREAD

**Issue by TianyuDai** [facebookresearch/multiface#10]
Thanks for sharing this dataset! 
I have read through [DATASET_ASSET](https://github.com/facebookresearch/multiface/blob/main/documentation/DATASET_ASSET.md) and [DATA_STRUCTURE](https://github.com/facebookresearch/multiface/blob/main/documentation/DATA_STRUCTURE.md), but cannot find the information about camera matrices unit. 
I assume that the first three rows (3x3 matrix) in KRT is the camera intrinsic. Is this intrinsic in unit of pixel? What is the fourth row (0.0 0.0 0.0 0.0 0.0)? Are the last three rows (3x4 matrix) the camera extrinsic? Are the translation in extrinsic shown in unit of millimeter? 
Are vertices coordinates in xxx.obj and translation in xxx_transform.txt also saved in unit of millimeter? 
In addition, what is the dtype and exact meaning of the values in xxx.bin? I noticed that they are slightly more than the number of vertices saved in xxx.obj. 
Thank you!

**Comment by cwuu** [comment]
Hi, 

The 3x4 matrix in the `transform.txt` is the projection matrix, which comes from multiplying camera intrinsic (3x3 matrix) with the camera extrinsic ([rotation|translation], 3x4 matrix). 
Aside from storing vertex values (which's the content of `.bin files`), `.obj files` also store the uv coordinate and the vertex topology. Storing data in binary format provides greater space-efficient and processing-efficient.

**Comment by TianyuDai** [comment]
Thank you for the quick answer!
