### ISSUE TITLE
Background image uesed in  Lombardi‘s MVP  not be found in multiface dataset

### ISSUE THREAD

**Issue by shuishiwojiade** [facebookresearch/multiface#11]
Multiface dataset has been used in "Mixture of Volumetric Primitives for Efficient Neural Rendering". The "mvp" onfig file needs the path to the background image. But I can't find the  background image in multiface dataset. 
The code in config file is:   bgpath = os.path.join(imagepathbase, 'bg', image', 'cam{cam}', 'image0000.png').

**Comment by cwuu** [comment]
Hi,

You may move this issue under MVP's repository such that the hosts of MVP repo would be able to handle your issue and give an update, thanks.

**Comment by cwuu** [comment]
Hi,

A quick update - here is the [link](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/MugsyDataRelease/MVP/bg_img.zip) to donwnload some background image.

For any following conversation, please move to the [thread](https://github.com/facebookresearch/mvp/issues/9) in MVP repo, thanks!
