### ISSUE TITLE
sequence of moving head pose 

### ISSUE THREAD

**Issue by baeckgoo** [facebookresearch/multiface#12]
Thank you for your work!

I'm finding frames with large variance of head pose within a specific user, expression, and camera in your dataset.
However, the majority of frames seem to have fixed head pose.

Although there are many camera view points, these are discrete.
Would you please suggest a sequence name that has continuous and moving head pose in this dataset?
(It was not easy to download and check it due to too large dataset size)

Thanks!

**Comment by vexilligera** [comment]
Hi, unfortunately I don't think there is a ROM sequence for headpose in this dataset.

**Comment by baeckgoo** [comment]
Thank you for reply!
