### ISSUE TITLE
Missing neutral peak for entity 5067077

### ISSUE THREAD

**Issue by songtoy** [facebookresearch/multiface#13]
Hi~ I couldn't find `EXP_neutral_peak` for entity 5067077 in the downloaded data. Can I find a replacement for neutral face in the data?

**Comment by songtoy** [comment]
Sorry if I made a mistake about whether `EXP_neutral_peak` means neutral face. I just need a neutral face as a template for each subject.

**Comment by vexilligera** [comment]
Hi, you could use the first frame of `E001 Neutral Eyes Open ` as a template.

**Comment by vexilligera** [comment]
Hi, you could use the first frame of `EXP_eye_neutral` as a template in this case.

**Comment by songtoy** [comment]
Got it. Many thanks~
