### ISSUE TITLE
keypoint index

### ISSUE THREAD

**Issue by taylorlu** [facebookresearch/multiface#14]
Can you provide the keypoints‘ index of 7,306 vertices in the mesh as described in paper.

**Comment by vexilligera** [comment]
cc Shoou-I,
@endoplasmic1357 Do we have any keypoint specifications from mesh barycentric coordinates that can be released?

**Comment by vexilligera** [comment]
Sorry for the late reply, currently we are not planning to release the keypoint specifications.
