### ISSUE TITLE
Audio Alignment

### ISSUE THREAD

**Issue by FreedomGu** [facebookresearch/multiface#15]
Hi, Thanks for sharing this fantastic dataset!

I was wondering if the audio is aligned with the images.

I downloaded audio and images and found some image parts of them are dropped.

Could you please tell me the frame rate you shot the videoes and how to align the data with audio by any chance?

**Comment by songtoy** [comment]
The frame rate should be 30, as mentioned in the paper. And I think the released data has been aligned with audio, though there are missing frames in some expressions.

**Comment by alexanderrichard** [comment]
The first available frame is aligned with the start of the audio file. You will have to account for dropped frames to keep audio-visual alignment in tact though.
