### ISSUE TITLE
how to get the average texture 

### ISSUE THREAD

**Issue by wangjue-wzq** [facebookresearch/multiface#16]
Hello, how to get the average texture data, such as follow.

https://github.com/facebookresearch/multiface/blob/31c5766069882ed59f1a01f8736074fc47eb64c0/dataset.py#L141

**Comment by cwuu** [comment]
Hi, 

average texture is generated by averaging over the unwrapped_texture of all frames, and thus will be unique for an entity. we pre-generated it and doesn't provide code to do so.
