### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by ChenLu2000** [facebookresearch/multiface#17]
Hi, thank you very much for open-sourcing this dataset! Really splendid work!

I have noticed that some of the follow-up works have used background images to model the background separately from the main target of reconstruction.
But it seems those images are not currently available in the dataset.

Do you have any plans to share them in the near future? Thanks again!

**Comment by cwuu** [comment]
Hi, 

here is the [link](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/MugsyDataRelease/MVP/bg_img.zip) to donwnload some background image.

For any following conversation, please move to the https://github.com/facebookresearch/mvp/issues/9 in MVP repo, thanks!
