### ISSUE TITLE
ROM for 002757580 and 002539136

### ISSUE THREAD

**Issue by kacperkan** [facebookresearch/multiface#18]
Hi, thank you for publishing the dataset!

I'm trying to use ROM and free_face sequences from the dataset. However, identities 002757580 and 002539136 don't have any of these. Is it possible that you could publish them?

Best,
kacperkan

**Comment by cwuu** [comment]
Hi,

As pointed out in [8](https://github.com/facebookresearch/multiface/blob/main/documentation/INSTALLATION.md), we don't provide testing set (either free_face or rom) for entity `002539136` and `002757580`.

**Comment by kacperkan** [comment]
Ok, thank you for the answer!
