### ISSUE TITLE
Sensor width in milimeters

### ISSUE THREAD

**Issue by kacperkan** [facebookresearch/multiface#22]
Hi everyone! Thank you for your great contribution by sharing the dataset.

I'm trying to visualize some NeRF results in Blender using training camera parameters. However, as far as I know, I need to know the sensor width in millimeters to match cameras reliably with the ones you used to capture the images. From my understanding, values in KRT file from `metadata` are in pixel space. Could you possibly share the sensor width in your setup?

**Comment by vexilligera** [comment]
Hello, I think the KRT units are in millimeters. See https://github.com/facebookresearch/multiface/issues/10
