### ISSUE TITLE
How to Feed Position Map to Network in PiCA

### ISSUE THREAD

**Issue by skyir0n** [facebookresearch/multiface#28]
Hello, I'm really interested in your work, especially Pixel Codec Avatar (PiCA).
Actually, it is very attractive work for me.

So, I'd like to ask a question regarding to the PiCA.

A coarse mesh is converted to position map and it is fed up into the encoder, instead of the mesh itself.
The position map obtained from the mesh, has high intensities of x, y, and z coordinates, respectively.
Generally, values of input data fed into a neural network belong to specific ranges. For example, RGB image has values ranging from 0 to 1.

Could you let me know how to feed the position map into the network?
Is a preprocessing needed such as normalization?

I would appreciate if you responds.
Thank you.

**Comment by alexanderrichard** [comment]
For PiCA, please reach out to the authors of the paper directly.
