### ISSUE TITLE
Need help to understand the metadata provided

### ISSUE THREAD

**Issue by Ling27** [facebookresearch/multiface#29]
Thank you very much for your work. It is interesting to see that your images contain rich details of facial skin. 

You have mentioned that head poses are provided. However, I did not find it in the downloaded dataset. Can you please tell me where to find it? In addition, there is a document "frame_list.txt" downloaded. Can you please help me understand this file? 

The screenshot of the downloaded data is attached. 

Thank you very much. 
![Screenshot 2023-04-26 112501](https://user-images.githubusercontent.com/39073722/234461809-6d98be4b-cf16-4842-a933-77aaac707b92.jpg)

**Comment by alexanderrichard** [comment]
Headposes are in the tracked_mesh directory. You will find .txt files that contain a 3x4 matrix for rotation + translation.

frame_list.txt is a file that contains all frames and the segments they belong to. For example, if the entry is "neutral 0028338" it means that frame 28338 is part of the neutral segment. The dataloader uses these files to parse the dataset and know how many/which frames are available.
