### ISSUE TITLE
Cannot access to the data server.

### ISSUE THREAD

**Issue by conallwang** [facebookresearch/multiface#37]
Thanks for your public data and great work!

I have downloaded facial data of several identities for research purposes before (several months ago). But today, I run the same download script and cannot access to the data server. Direct access using Chrome Browser also doesn't work (see the following figure).

Is there any error with the data server? 

<img width="1562" alt="image" src="https://github.com/facebookresearch/multiface/assets/31753943/af106d6e-595f-412a-9670-1ffeb9fdd2c2">

**Comment by chinmaychinara91** [comment]
I tried downloading as well. The same error can be seen.

**Comment by ChenWang8750** [comment]
Using code download also reports an error.

![微信截图_20230808091200](https://github.com/facebookresearch/multiface/assets/86447049/e834b226-0f4b-4da7-9ab5-f9a1080c8501)

**Comment by conallwang** [comment]
It seems to work now. I close this issue.
