### ISSUE TITLE
Typo in download_dataset.py

### ISSUE THREAD

**Issue by TianyuDai** [facebookresearch/multiface#4]
Hi, 
Thank you for making the dataset public! 
I tried to download the mini-dataset following the instruction, but fell into an infinite loop. 
Should [line 65](https://github.com/facebookresearch/multiface/blob/890a567682ea077f171ebc75eae48a4ed974c634/download_dataset.py#L65) in download_dataset.py be `if os.path.isfile("%s.checksum" % (tar_file))`?

**Comment by FreedomGu** [comment]
I had the same issues in downloading mini-dataset as well.

**Comment by FreedomGu** [comment]
And seems like both of /path/to/mini-dataset and /path/to/dataset doesn't exists?

**Comment by alexanderrichard** [comment]
Apologies for the inconvenience. We will fix the bug asap.

**Comment by Luh1124** [comment]
It can be changed to os.path.exits()

**Comment by vexilligera** [comment]
> And seems like both of /path/to/mini-dataset and /path/to/dataset doesn't exists?

Hi, that is for you to replace with the path to your downloaded dataset. Thank you.

**Comment by cwuu** [comment]
> Hi, Thank you for making the dataset public! I tried to download the mini-dataset following the instruction, but fell into an infinite loop. Should [line 65](https://github.com/facebookresearch/multiface/blob/890a567682ea077f171ebc75eae48a4ed974c634/download_dataset.py#L65) in download_dataset.py be `if os.path.isfile("%s.checksum" % (tar_file))`?

Hi, Thanks for pointing this out. `download_dataset.py` is updated and added the condition to avoid possible infinite loop.
