### ISSUE TITLE
Error when download ths mini-dataset

### ISSUE THREAD

**Issue by Tankaishen** [facebookresearch/multiface#42]
INFO:root:Downloaded /path/to/mini_dataset/6795937unwrapped_uv_1024--E061_Lips_Puffed.tar failed. Re-downloading...
/path/to/mini_dataset/6795937unwrapped_uv_1024--E061_Lips_Puffed.tar: No such file or directory
INFO:root:Downloaded /path/to/mini_dataset/6795937unwrapped_uv_1024--E061_Lips_Puffed.tar failed. Re-downloading...
/path/to/mini_dataset/6795937unwrapped_uv_1024--E061_Lips_Puffed.tar: No such file or directory
INFO:root:Downloaded /path/to/mini_dataset/6795937unwrapped_uv_1024--E061_Lips_Puffed.tar failed. Re-downloading...
Traceback (most recent call last):
  File "download_dataset.py", line 214, in <module>
    main(args)
  File "download_dataset.py", line 181, in main
    if download_tar(
  File "download_dataset.py", line 155, in download_tar
    excluded_tar_files = checksum(tar_files, download_dest, entity, checksum_file)
  File "download_dataset.py", line 49, in checksum
    checksum_file = open("%s" % (checksum_file), "r")
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/mini_dataset/6795937CHECKSUM'
When run "python3 download_dataset.py --dest "/path/to/mini_dataset/" --download_config "./mini_download_config.json"", there occur the error, in which the last several infomation has been shown above.

**Comment by FarzanehJafari1987** [comment]
Create a mini_dataset folder in the MULTIFACE directory and try this line:
python3 download_dataset.py --dest "mini_dataset" --download_config "./mini_download_config.json"

**Comment by Tankaishen** [comment]
I get it
