### ISSUE TITLE
How to generate an average texture from the multi-camera textures in unwrapped_uv_1024

### ISSUE THREAD

**Issue by shuishiwojiade** [facebookresearch/multiface#5]
Thanks for your great works!
I have downloaded the mini-dataset. I'm interested in generating an average texture in average folder from the multi-camera textures in unwrapped_uv_1024 folder.

**Comment by alexanderrichard** [comment]
The average texture is just the average over all view-dependent textures. You might want to exclude the invisible parts (purely black areas of a view-dependent textures) from the averaging so you get a fair weighting of the average texel value on the texture.

**Comment by cwuu** [comment]
Hi, 

You may also use the average texture on all expression&camera to approximate the result. You can [download the metadata.tar](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/MugsyDataRelease/v0.0/identities/6795937/metadata.tar
) and get the `tex_mean.png` from it, thanks!

**Comment by cwuu** [comment]
Hi, 

It turns out that there's a bug in the `download_dataset.py` such that the metadata of the associated entity is not downloaded. The error is fixed and you should be able to get the average texture` tex_mean.png` directly by running the mini dataset download commend, thanks!
