### ISSUE TITLE
.bin and .txt files of the tracked mesh

### ISSUE THREAD

**Issue by wwpokenet** [facebookresearch/multiface#6]
Thanks for sharing this dataset!

I'm wondering what's the .bin and .txt files in the tracked mesh folder? Like 
`./m--20171024--0000--002757580--GHS/tracked_mesh/E002_Swallow/[000431.bin, 000431_transform.txt]`

**Comment by cwuu** [comment]
Hi,

`transform.txt` is a 3x4 matrix consiting of rotation and translation that represents the rigid body transformation of the head mesh at each frame. and `.bin `file contains the per frame vertex.
