### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by danthe13th** [facebookresearch/multiface#8]
the tool is really amazing. 
im wondering if there is anyway to run this tool on termux?

**Comment by vexilligera** [comment]
I assume you are referring to https://termux.dev/en/ ? I believe if you wish to run the models in this repo you'll have to figure out the dependencies on that platform which is not supported. If you only wish to download the data on termux then I think you'll only need Python environment and install the packages in `requirements.txt`. Thank you.
