### ISSUE TITLE
Downloading with mini_download_config.json

### ISSUE THREAD

**Issue by baeckgoo** [facebookresearch/multiface#9]
Thanks for sharing your work.

I tried downloading mini dataset using the following command.
```
python3 download_dataset.py --dest "/mypath/to/mini_dataset/" --download_config "./mini_download_config.json"
```
However, only 'images', 'tracked meshes', and 'unwrapped_uv_1024'  were downloaded.
Meta data and others  were not downloaded.
How can I download all information for mini dataset?

Thanks.

**Comment by cwuu** [comment]
Hi,

Thanks for pointing this out! We've fixed the error in `downlaod_dataset.py`, and you should be able to get the meta data and audio file by running `python3 download_dataset.py --dest "/mypath/to/mini_dataset/" --download_config "./mini_download_config.json"`. Let me know if you have any further questions, thanks!
